#!/bin/bash
# Compatibility with Odoo 10
# where the 'odoo.py' command is renamed to 'odoo'.
#
# All the local scripts use 'odoo' so we can
# be compatible with both versions

set -e

exec openerp-server "$@"
