MAINTAINER Camptocamp

WORKDIR "/odoo"
COPY ./extra_requirements.txt ./

# Install extra requirement
RUN set -x; \
        /install/dev_package.sh \
        && pip install --disable-pip-version-check -r extra_requirements.txt \
        && /install/purge_dev_package_and_cache.sh

WORKDIR "/"
