#!/bin/bash

DOMAIN="${ODOO_BASE_URL}"

if [ -n "$DOMAIN" ]; then

  if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" )" != '1' ]
  then
      echo "Database does not exist, ignoring script"
      exit 0
  fi

  echo "Setting Base URL to domain ${DOMAIN}"
  psql --quiet << EOF

  WITH update_param AS (
    UPDATE ir_config_parameter
    SET value = '${DOMAIN}'
    WHERE key = 'web.base.url'
    RETURNING *
  )
  INSERT INTO ir_config_parameter
  (value, key, create_uid, write_uid, create_date, write_date)
  SELECT '${DOMAIN}', 'web.base.url', 1, 1, now(), now()
  WHERE NOT EXISTS (SELECT * FROM update_param);

  WITH update_param AS (
    UPDATE ir_config_parameter
    SET value = 'True'
    WHERE key = 'web.base.url.freeze'
    RETURNING *
  )
  INSERT INTO ir_config_parameter
  (value, key, create_uid, write_uid, create_date, write_date)
  SELECT 'True', 'web.base.url.freeze', 1, 1, now(), now()
  WHERE NOT EXISTS (SELECT * FROM update_param);

EOF
fi
