#!/bin/bash
if [ "${ODOO_VERSION%%.*}" -lt 16 ]; then
    echo "Neutralization skipped: requires Odoo 16.0+"
    exit 0
fi
# Default value
ODOO_NEUTRALIZE=${ODOO_NEUTRALIZE:-True}
if [[ "$RUNNING_ENV" != "prod" && "$ODOO_NEUTRALIZE" == "True" ]]; then
    if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" )" != '1' ]
    then
        echo "Database does not exist, ignoring script"
        exit 0
    fi
    if [ "$( psql -tAc "SELECT value FROM ir_config_parameter WHERE key='database.is_neutralized'" )" = 'True' ]; then
        echo "Database is already neutralized, skipping"
        exit 0
    fi
    odoo neutralize
fi
