#! /bin/bash

# This script can be removed when we have finished updating databases with
# the configuration of the unaccent extension (Odoo >= 16)
# And when changes for res.partner are included in Odoo

if [ "${ODOO_VERSION%%.*}" -lt 16 -o "${ODOO_VERSION%%.*}" -gt 19 ]; then
    echo "Index fixing for unaccent: requires Odoo 16 to 19"
    exit 0
fi

WHERE_CLAUSE="WHERE indexdef LIKE '%gin_trgm_ops%' AND indexname LIKE '%_index' AND schemaname = current_schema"
WITHOUT_UNACCENT="AND indexdef NOT LIKE '%unaccent%'"
# Skip special 'ir_attachment_url_trgm_index' from camptocamp/odoo-tools, Odoo 16 and 17
WITHOUT_UNACCENT="$WITHOUT_UNACCENT AND indexname != 'ir_attachment_url_trgm_index'"

# Any trigram index without unaccent?
if [ 0 = $(psql -tAc "SELECT COUNT(*) FROM pg_indexes $WHERE_CLAUSE $WITHOUT_UNACCENT;") ]; then
    # Missing trigram on "res.partner"? (at least 6 trigram indexes are expected)
    if [ "$(psql -tAc "SELECT COUNT(*) FROM pg_indexes $WHERE_CLAUSE AND tablename = 'res_partner';")" -gt 5 ]; then
       echo "No indexes to fix"
       exit 0
    fi
fi

odoo shell --no-http --log-handler=:ERROR --log-handler=odoo.schema:INFO << EOF
import re

# Fix for "res.partner": fields which were not declared index="trigram"
# ["name", "complete_name", "email", "ref", "vat", "company_registry"]
# For Odoo >= 19, search uses "complete_name" instead of "display_name"
res_partner = env["res.partner"]
res_partner_trigram = ["name"] + res_partner._rec_names_search
for field_name in res_partner_trigram:
    field = res_partner._fields[field_name]
    if field.index != "trigram":
        field.index = "trigram"


# Inspired by 'env.registry.check_indexes()' implementation
expected = {
    (model_name, field)
    for model_name in env
    for model in (env[model_name],)
    if model._auto and not model._abstract
    for field in model._fields.values()
    if field.column_type and field.store and field.index == "trigram"
}
existing = set()

# "res.partner" boolean field "active" should be indexed
field_active = res_partner._fields["active"]
if not field_active.index:
    field_active.index = "btree"
    expected.add(("res.partner", field_active))


def find_model(tablename):
    model_name = tablename.replace("_", ".")
    if model_name in env and env[model_name]._table == tablename:
        return env[model_name]
    for model_name in env:
        if env[model_name]._table == tablename:
            return env[model_name]


query = """\
SELECT indexname, tablename, indexdef FROM pg_indexes
 WHERE indexname LIKE '%_index' AND schemaname = current_schema
   AND (tablename = 'res_partner' OR indexdef LIKE '%gin_trgm_ops%');
"""
env.cr.execute(query)

for indexname, tablename, indexdef in env.cr.fetchall():
    # Odoo >= 17 uses '__' as separator between table and column
    # Note that index names longer than 63 chars are mangled, hence they are not detected
    parsed = re.match(f"{tablename}__?(.+)_index", indexname)

    # Sanity check, to avoid dropping non-standard indexes
    colname = parsed and parsed.group(1)
    if not colname:
        continue
    model = find_model(tablename)
    field = model is not None and model._fields.get(colname)
    if not field:
        continue
    field_key = (model._name, field)
    if field_key not in expected:
        continue
    if "unaccent" in indexdef or field_key == ("res.partner", field_active):
        existing.add(field_key)
    else:
        print(f"Fixing index {indexname} on table {tablename} ({colname})")
        env.cr.execute(f"DROP INDEX {indexname};")

model_names = {name for (name, __) in expected - existing}

if model_names:
    # recreate the indexes with unaccent
    for model in model_names:
        print(f"Restore indexes for {model}")
    env.registry.check_indexes(env.cr, model_names)
else:
    print("No index to create")

env.cr.commit()
EOF
